import { Bot, Sparkles } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/EmptyState";
import type { AIInsight } from "@/types/api.types";

interface AIInsightCardProps {
  insight: AIInsight | null | undefined;
}

export function AIInsightCard({ insight }: AIInsightCardProps) {
  return (
    <Card className="overflow-hidden rounded-xl border-border border-l-[3px] border-l-primary bg-gradient-to-br from-card to-[#fafcfd] shadow-[var(--shadow-xs)]">
      <CardHeader className="flex flex-row items-center gap-2 pb-2">
        <Bot className="size-5 text-primary" />
        <CardTitle className="text-sm font-semibold">AI Insight</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {insight ? (
          <>
            <p className="text-sm leading-relaxed text-[#292524]">
              {insight.summary}
            </p>
            {insight.riskFlags.length > 0 && (
              <div className="flex flex-wrap gap-2">
                {insight.riskFlags.map((flag) => (
                  <Badge
                    key={flag}
                    variant="outline"
                    className="border-amber-200 bg-amber-50 text-amber-800"
                  >
                    {flag}
                  </Badge>
                ))}
              </div>
            )}
            <p className="text-xs text-[#a8a29e]">Generated by Claude</p>
          </>
        ) : (
          <EmptyState
            icon={Sparkles}
            title="Insight not ready"
            description="Available after the PR is merged or receives at least 2 reviews."
          />
        )}
      </CardContent>
    </Card>
  );
}
